# Generated by Django 5.1.4 on 2025-01-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product1',
        ),
    ]
