# Generated by Django 5.1.4 on 2025-01-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_view2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view2',
            old_name='category',
            new_name='gcategory',
        ),
        migrations.RenameField(
            model_name='view2',
            old_name='pname',
            new_name='gname',
        ),
        migrations.RenameField(
            model_name='view2',
            old_name='price',
            new_name='gprice',
        ),
        migrations.RemoveField(
            model_name='view2',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='view2',
            name='pimage',
        ),
    ]
