# Generated by Django 5.1.4 on 2025-01-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view1',
            old_name='pimage',
            new_name='rimage',
        ),
        migrations.RenameField(
            model_name='view1',
            old_name='pname',
            new_name='rname',
        ),
    ]
