# Generated by Django 5.1.4 on 2025-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_acce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acce',
        ),
        migrations.DeleteModel(
            name='view1',
        ),
        migrations.DeleteModel(
            name='View2',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Protein'), (2, 'Gainer'), (3, 'Creatine'), (4, 'BCAA'), (5, 'EAA'), (6, 'Fish Oil'), (7, 'Pre-Workout'), (8, 'Peanut-Butter'), (9, 'Oats'), (10, 'Muesli'), (11, 'Muesli'), (12, 'Shaker'), (13, 'Sandbag'), (14, 'Weightlifting Belt'), (15, 'Hand-Glooves')], verbose_name='Category'),
        ),
    ]
