# Generated by Django 5.1.4 on 2025-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_product_pimage1_product_pimage2_product_price1'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt1y', models.IntegerField(default=1)),
            ],
        ),
    ]
