# Generated by Django 5.1.4 on 2025-02-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_cart1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart1',
        ),
    ]
