# Generated by Django 5.1.4 on 2025-02-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_bmicalculation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BMICalculation',
        ),
    ]
