# Generated by Django 5.1.4 on 2025-02-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_bmirecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmirecord',
            name='height',
            field=models.FloatField(help_text='Height in cm'),
        ),
    ]
